[package]
name = "generated"
version = "0.1.0"
edition = "2021"

[build-dependencies]
defines_generator = { path = "../prototype/defines/defines_generator" }
prototypes_generator = { path = "../prototype/prototypes/prototypes_generator" }
types_generator = { path = "../prototype/types/types_generator" }

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_repr = "0.1.19"
