[package]
name = "generated"
version = "0.1.0"
edition = "2021"

[build-dependencies]
defines_generator = { path = "../defines/defines_generator" }
types_generator = { path = "../types/types_generator" }

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_repr = "0.1.19"
